# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Stockly' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stockly

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'LBTAComponents'
pod 'JGProgressHUD'
pod 'SwiftyJSON'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'Alamofire', '~> 5.0.0-beta.5'
pod 'DropDown'

end
